-- Migration: Seed districts
-- Description: Populates districts with corresponding region relationships in an idempotent way.

WITH new_districts (region_code, code, name_uz_latn, name_uz_cyrl, name_ru, name_en) AS (
  VALUES
    -- Andijan (AND)
    ('AND', 'AND_AND_C', 'Andijon shahri', 'Андижон шаҳри', 'город Андижан', 'Andijan City'),
    ('AND', 'AND_XON_C', 'Xonabod shahri', 'Хонабод шаҳри', 'город Ханабад', 'Xonabod City'),
    ('AND', 'AND_AND_D', 'Andijon tumani', 'Андижон тумани', 'Андижанский район', 'Andijan District'),
    ('AND', 'AND_ASA_D', 'Asaka tumani', 'Асака тумани', 'Асакинский район', 'Asaka District'),
    ('AND', 'AND_BAL_D', 'Baliqchi tumani', 'Балиқчи тумани', 'Балыкчинский район', 'Baliqchi District'),
    ('AND', 'AND_BOS_D', 'Bo''ston tumani', 'Бўстон тумани', 'Бустанский район', 'Buston District'),
    ('AND', 'AND_BUL_D', 'Buloqboshi tumani', 'Булоқбоши тумани', 'Булакбашинский район', 'Buloqboshi District'),
    ('AND', 'AND_JAL_D', 'Jalaquduq tumani', 'Жалақудуқ тумани', 'Джалалкудукский район', 'Jalaquduq District'),
    ('AND', 'AND_IZB_D', 'Избоскан tumani', 'Избоскан тумани', 'Избасканский район', 'Izboskan District'),
    ('AND', 'AND_MAR_D', 'Marhamat tumani', 'Марҳамат тумани', 'Мархаматский район', 'Marhamat District'),
    ('AND', 'AND_OLT_D', 'Oltinko''l tumani', 'Олтинкўл тумани', 'Алтынкульский район', 'Oltinkul District'),
    ('AND', 'AND_PAX_D', 'Paxtaobod tumani', 'Пахтаобод тумани', 'Пахтаабадский район', 'Paxtaobod District'),
    ('AND', 'AND_ULU_D', 'Ulug''nor tumani', 'Улуғнор тумани', 'Улугнорский район', 'Ulugnor District'),
    ('AND', 'AND_XOJ_D', 'Xўjaobod tumani', 'Хўжаобод тумани', 'Ходжаабадский район', 'Xojaobod District'),
    ('AND', 'AND_SHA_D', 'Shahrixon tumani', 'Шаҳрихон тумани', 'Шахриханский район', 'Shahrixon District'),
    ('AND', 'AND_QOR_D', 'Qo''rg''ontepa tumani', 'Қўрғонтепа тумани', 'Кургантепинский район', 'Qurgontepa District'),

    -- Bukhara (BUX)
    ('BUX', 'BUX_BUX_C', 'Buxoro shahri', 'Бухоро шаҳри', 'город Бухара', 'Bukhara City'),
    ('BUX', 'BUX_KOG_C', 'Kogon shahri', 'Когон шаҳри', 'город Каган', 'Kogon City'),
    ('BUX', 'BUX_BUX_D', 'Buxoro tumani', 'Бухоро тумани', 'Бухарский район', 'Bukhara District'),
    ('BUX', 'BUX_VOB_D', 'Vobkent tumani', 'Вобкент тумани', 'Вабкентский район', 'Vobkent District'),
    ('BUX', 'BUX_JON_D', 'Jondor tumani', 'Жондор тумани', 'Жондорский район', 'Jondor District'),
    ('BUX', 'BUX_KOG_D', 'Kogon tumani', 'Когон тумани', 'Каганский район', 'Kogon District'),
    ('BUX', 'BUX_OLO_D', 'Olot tumani', 'Олот тумани', 'Алатский район', 'Olot District'),
    ('BUX', 'BUX_PES_D', 'Peshku tumani', 'Пешку тумани', 'Пешкунский район', 'Peshku District'),
    ('BUX', 'BUX_ROM_D', 'Romitan tumani', 'Ромитан тумани', 'Ромитанский район', 'Romitan District'),
    ('BUX', 'BUX_SHO_D', 'Shofirkon tumani', 'Шофиркон тумани', 'Шафирканский район', 'Shofirkon District'),
    ('BUX', 'BUX_QOV_D', 'Qorovulbozor tumani', 'Қоровулбозор тумани', 'Караулбазарский район', 'Qorovulbozor District'),
    ('BUX', 'BUX_QOR_D', 'Qorako''l tumani', 'Қоракўл тумани', 'Каракульский район', 'Qorakol District'),
    ('BUX', 'BUX_GIJ_D', 'G''ijduvon tumani', 'Ғиждувон тумани', 'Гиждуванский район', 'Gijduvon District'),

    -- Fergana (FER)
    ('FER', 'FER_FER_C', 'Farg''ona shahri', 'Фарғона шаҳри', 'город Фергана', 'Fergana City'),
    ('FER', 'FER_MAR_C', 'Marg''ilon shahri', 'Марғилон шаҳри', 'город Маргилан', 'Margilon City'),
    ('FER', 'FER_QOQ_C', 'Qo''qon shahri', 'Қўқон шаҳри', 'город Коканд', 'Qoqon City'),
    ('FER', 'FER_QUV_C', 'Quvasoy shahri', 'Қувасой шаҳри', 'город Кувасай', 'Quvasoy City'),
    ('FER', 'FER_BOG_D', 'Bog''dod tumani', 'Боғдод тумани', 'Багдадский район', 'Bogdod District'),
    ('FER', 'FER_BES_D', 'Beshariq tumani', 'Бешариқ тумани', 'Бешарыкский район', 'Beshariq District'),
    ('FER', 'FER_BUV_D', 'Buvayda tumani', 'Бувайда тумани', 'Бувайдинский район', 'Buvayda District'),
    ('FER', 'FER_DAN_D', 'Данғара tumani', 'Данғара тумани', 'Дангаринский район', 'Dangara District'),
    ('FER', 'FER_YOZ_D', 'Yozyovon tumani', 'Ёзёвон тумани', 'Язъяванский район', 'Yozyovon District'),
    ('FER', 'FER_QUV_D', 'Quva tumani', 'Қува тумани', 'Кувинский район', 'Quva District'),
    ('FER', 'FER_OLT_D', 'Oltiariq tumani', 'Олтиариқ тумани', 'Алтыарыкский район', 'Oltiariq District'),
    ('FER', 'FER_QOS_D', 'Qo''shtepa tumani', 'Қўштепа тумани', 'Куштепинский район', 'Qoshtepa District'),
    ('FER', 'FER_RIS_D', 'Rishton tumani', 'Риштон тумани', 'Риштанский район', 'Rishton District'),
    ('FER', 'FER_SOX_D', 'So''x tumani', 'Сўх тумани', 'Сохский район', 'Sox District'),
    ('FER', 'FER_TOS_D', 'Toshloq tumani', 'Тошлоқ тумани', 'Ташлакский район', 'Toshloq District'),
    ('FER', 'FER_UCH_D', 'Uchko''prik tumani', 'Учкўприк тумани', 'Учкуприкский район', 'Uchkoprik District'),
    ('FER', 'FER_FER_D', 'Farg''ona tumani', 'Фарғона тумани', 'Ферганский район', 'Fergana District'),
    ('FER', 'FER_FUR_D', 'Furqat tumani', 'Фурқат тумани', 'Фуркатский район', 'Furqat District'),
    ('FER', 'FER_OZB_D', 'O''zbekiston tumani', 'Ўзбекистон тумани', 'Узбекистанский район', 'Uzbekiston District'),

    -- Jizzakh (JIZ)
    ('JIZ', 'JIZ_JIZ_C', 'Jizzax shahri', 'Жиззах шаҳри', 'город Джизак', 'Jizzakh City'),
    ('JIZ', 'JIZ_ARN_D', 'Arnasoy tumani', 'Арнасой тумани', 'Арнасайский район', 'Arnasoy District'),
    ('JIZ', 'JIZ_BAX_D', 'Baxmal tumani', 'Бахмал тумани', 'Бахмальский район', 'Baxmal District'),
    ('JIZ', 'JIZ_GAL_D', 'G''allaorol tumani', 'Ғаллаорол тумани', 'Галляаральский район', 'Gallaorol District'),
    ('JIZ', 'JIZ_SHA_D', 'Sharof Rashidov tumani', 'Шароф Рашидов тумани', 'Шараф-Рашидовский район', 'Sharof Rashidov District'),
    ('JIZ', 'JIZ_DOS_D', 'Do''stlik tumani', 'Дўстлик тумани', 'Дустликский район', 'Dostlik District'),
    ('JIZ', 'JIZ_ZOM_D', 'Zomin tumani', 'Зомин тумани', 'Зааминский район', 'Zomin District'),
    ('JIZ', 'JIZ_ZAR_D', 'Zarbdor tumani', 'Зарбдор тумани', 'Зарбдарский район', 'Zarbdor District'),
    ('JIZ', 'JIZ_ZAF_D', 'Zafarobod tumani', 'Зафаробод тумани', 'Зафарабадский район', 'Zafarobod District'),
    ('JIZ', 'JIZ_MIR_D', 'Mirzacho''l tumani', 'Мирзачўл тумани', 'Мирзачульский район', 'Mirzachol District'),
    ('JIZ', 'JIZ_PAX_D', 'Paxtakor tumani', 'Пахтакор тумани', 'Пахтакорский район', 'Paxtakor District'),
    ('JIZ', 'JIZ_FOR_D', 'Forish tumani', 'Фориш тумани', 'Фаришский район', 'Forish District'),
    ('JIZ', 'JIZ_YAN_D', 'Yangiobod tumani', 'Янгиобод тумани', 'Янгиабадский район', 'Yangiobod District'),

    -- Namangan (NAM)
    ('NAM', 'NAM_NAM_C', 'Namangan shahri', 'Наманган шаҳри', 'город Наманган', 'Namangan City'),
    ('NAM', 'NAM_MIN_D', 'Mingbuloq tumani', 'Мингбулоқ тумани', 'Мингбулакский район', 'Mingbuloq District'),
    ('NAM', 'NAM_KOS_D', 'Kosonsoy tumani', 'Косонсой тумани', 'Касансайский район', 'Kosonsoy District'),
    ('NAM', 'NAM_NAM_D', 'Namangan tumani', 'Наманган тумани', 'Наманганский район', 'Namangan District'),
    ('NAM', 'NAM_NOR_D', 'Norin tumani', 'Норин тумани', 'Нарынский район', 'Norin District'),
    ('NAM', 'NAM_POP_D', 'Pop tumani', 'Поп тумани', 'Папский район', 'Pop District'),
    ('NAM', 'NAM_TOR_D', 'To''raqo''rg''on tumani', 'Тўрақўрғон тумани', 'Туракурганский район', 'Turaqurgon District'),
    ('NAM', 'NAM_UYC_D', 'Uychi tumani', 'Уйчи тумани', 'Уйчинский район', 'Uychi District'),
    ('NAM', 'NAM_UCH_D', 'Uchqo''rg''on tumani', 'Учқўрғон тумани', 'Учкурганский район', 'Uchqurgon District'),
    ('NAM', 'NAM_CHO_D', 'Chortoq tumani', 'Чортоқ тумани', 'Чартакский район', 'Chortoq District'),
    ('NAM', 'NAM_CHU_D', 'Chust tumani', 'Чуст тумани', 'Чустский район', 'Chust District'),
    ('NAM', 'NAM_YAN_D', 'Yangiqo''rg''on tumani', 'Янгиқўрғон тумани', 'Янгикурганский район', 'Yangiqurgon District'),
    ('NAM', 'NAM_DAV_D', 'Davlatobod tumani', 'Давлатобод тумани', 'Давлатабадский район', 'Davlatobod District'),
    ('NAM', 'NAM_YNA_D', 'Yangi Namangan tumani', 'Янги Наманган тумани', 'Янги Наманганский район', 'Yangi Namangan District'),

    -- Navoiy (NAV)
    ('NAV', 'NAV_NAV_C', 'Navoiy shahri', 'Навоий шаҳри', 'город Навои', 'Navoiy City'),
    ('NAV', 'NAV_ZAR_C', 'Zarafshon shahri', 'Зарафшон шаҳри', 'город Зарафшан', 'Zarafshon City'),
    ('NAV', 'NAV_GOZ_C', 'G''ozg''on shahri', 'Ғозғон шаҳри', 'город Газган', 'Gozgon City'),
    ('NAV', 'NAV_KON_D', 'Konimex tumani', 'Конимех тумани', 'Канимехский район', 'Konimex District'),
    ('NAV', 'NAV_KAR_D', 'Karmana tumani', 'Кармана тумани', 'Карманинский район', 'Karmana District'),
    ('NAV', 'NAV_QIZ_D', 'Qiziltepa tumani', 'Қизилтепа тумани', 'Кызылтепинский район', 'Qiziltepa District'),
    ('NAV', 'NAV_XAT_D', 'Xatirchi tumani', 'Хатирчи тумани', 'Хатырчинский район', 'Xatirchi District'),
    ('NAV', 'NAV_NAB_D', 'Navbahor tumani', 'Навбаҳор тумани', 'Навбахорский район', 'Navbahor District'),
    ('NAV', 'NAV_NUR_D', 'Nurota tumani', 'Нурота тумани', 'Нуратинский район', 'Nurota District'),
    ('NAV', 'NAV_TOM_D', 'Tomdi tumani', 'Томди тумани', 'Тамдынский район', 'Tomdi District'),
    ('NAV', 'NAV_UCH_D', 'Uchquduq tumani', 'Учқудуқ тумани', 'Учкудукский район', 'Uchquduq District'),

    -- Qashqadaryo (QAS)
    ('QAS', 'QAS_QAR_C', 'Qarshi shahri', 'Қарши шаҳри', 'город Карши', 'Qarshi City'),
    ('QAS', 'QAS_SHA_C', 'Shahrisabz shahri', 'Шаҳрисабз шаҳри', 'город Шахрисабз', 'Shahrisabz City'),
    ('QAS', 'QAS_GUZ_D', 'G''uzor tumani', 'Ғузор тумани', 'Гузарский район', 'Guzor District'),
    ('QAS', 'QAS_DEH_D', 'Dehqonobod tumani', 'Деҳқонобод тумани', 'Дехканабадский район', 'Dehqonobod District'),
    ('QAS', 'QAS_QAM_D', 'Qamashi tumani', 'Қамаши тумани', 'Камашинский район', 'Qamashi District'),
    ('QAS', 'QAS_QAR_D', 'Qarshi tumani', 'Қарши тумани', 'Каршинский район', 'Qarshi District'),
    ('QAS', 'QAS_KOS_D', 'Koson tumani', 'Косон тумани', 'Касанский район', 'Koson District'),
    ('QAS', 'QAS_KIT_D', 'Kitob tumani', 'Китоб тумани', 'Китабский район', 'Kitob District'),
    ('QAS', 'QAS_MIR_D', 'Миришкор tumani', 'Миришкор тумани', 'Миришкорский район', 'Mirishkor District'),
    ('QAS', 'QAS_MUB_D', 'Muborak tumani', 'Муборак тумани', 'Мубарекский район', 'Muborak District'),
    ('QAS', 'QAS_NIS_D', 'Nishon tumani', 'Нишон тумани', 'Нишанский район', 'Nishon District'),
    ('QAS', 'QAS_KAS_D', 'Kasbi tumani', 'Касби тумани', 'Касбийский район', 'Kasbi District'),
    ('QAS', 'QAS_KOK_D', 'Ko''kdala tumani', 'Кўкдала тумани', 'Кукдалинский район', 'Kokdala District'),
    ('QAS', 'QAS_YAK_D', 'Yakkabog'' tumani', 'Яккабоғ тумани', 'Яккабагский район', 'Yakkabog District'),
    ('QAS', 'QAS_SHA_D', 'Shahrisabz tumani', 'Шаҳрисабз тумани', 'Шахрисабзский район', 'Shahrisabz District'),
    ('QAS', 'QAS_CHI_D', 'Chiroqchi tumani', 'Чироқчи тумани', 'Чиракчинский район', 'Chiroqchi District'),

    -- Samarqand (SAM)
    ('SAM', 'SAM_SAM_C', 'Samarqand shahri', 'Самарқанд шаҳри', 'город Самарканд', 'Samarqand City'),
    ('SAM', 'SAM_KAT_C', 'Kattaqo''rg''on shahri', 'Каттақўрғон шаҳри', 'город Каттакурган', 'Kattaqurgon City'),
    ('SAM', 'SAM_BUL_D', 'Bulung''ur tumani', 'Булунғур тумани', 'Булунгурский район', 'Bulungur District'),
    ('SAM', 'SAM_ISH_D', 'Ishtixon tumani', 'Иштихон тумани', 'Иштиханский район', 'Ishtixon District'),
    ('SAM', 'SAM_JOM_D', 'Jomboy tumani', 'Жомбой тумани', 'Джамбайский район', 'Jomboy District'),
    ('SAM', 'SAM_KAT_D', 'Kattaqo''rg''on tumani', 'Каттақўрғон тумани', 'Каттакурганский район', 'Kattaqurgon District'),
    ('SAM', 'SAM_QOS_D', 'Qo''shrabot tumani', 'Қўшработ тумани', 'Кошрабадский район', 'Qoshrabot District'),
    ('SAM', 'SAM_NAR_D', 'Narpay tumani', 'Нарпай тумани', 'Нарпайский район', 'Narpay District'),
    ('SAM', 'SAM_NUR_D', 'Nurobod tumani', 'Нуробод тумани', 'Нурабадский район', 'Nurobod District'),
    ('SAM', 'SAM_OQD_D', 'Oqdaryo tumani', 'Оқдарё тумани', 'Акдарьинский район', 'Oqdaryo District'),
    ('SAM', 'SAM_PAX_D', 'Paxtachi tumani', 'Пахтачи тумани', 'Пахтачийский район', 'Paxtachi District'),
    ('SAM', 'SAM_PAY_D', 'Payariq tumani', 'Пайариқ тумани', 'Пайарыкский район', 'Payariq District'),
    ('SAM', 'SAM_PAS_D', 'Pastdarg''om tumani', 'Пастдарғом тумани', 'Пастдаргомский район', 'Pastdargom District'),
    ('SAM', 'SAM_SAM_D', 'Samarqand tumani', 'Самарқанд тумани', 'Самаркандский район', 'Samarqand District'),
    ('SAM', 'SAM_TOY_D', 'Toyloq tumani', 'Тойлоқ тумани', 'Тайлакский район', 'Toyloq District'),
    ('SAM', 'SAM_URG_D', 'Urgut tumani', 'Ургут тумани', 'Ургутский район', 'Urgut District'),

    -- Sirdaryo (SIR)
    ('SIR', 'SIR_GUL_C', 'Guliston shahri', 'Гулистон шаҳри', 'город Гулистан', 'Guliston City'),
    ('SIR', 'SIR_YAN_C', 'Yangiyer shahri', 'Янгиер шаҳри', 'город Янгиер', 'Yangiyer City'),
    ('SIR', 'SIR_SHI_C', 'Shirin shahri', 'Ширин шаҳри', 'город Ширин', 'Shirin City'),
    ('SIR', 'SIR_OQO_D', 'Oqoltin tumani', 'Оқолтин тумани', 'Акалтынский район', 'Oqoltin District'),
    ('SIR', 'SIR_BOY_D', 'Boyovut tumani', 'Боёвут тумани', 'Баяутский район', 'Boyovut District'),
    ('SIR', 'SIR_GUL_D', 'Guliston tumani', 'Гулистон тумани', 'Гулистанский район', 'Guliston District'),
    ('SIR', 'SIR_XAV_D', 'Xavos tumani', 'Хавос тумани', 'Хавастский район', 'Xavos District'),
    ('SIR', 'SIR_MIR_D', 'Mirzaobod tumani', 'Мирзаобод тумани', 'Мирзаабадский район', 'Mirzaobod District'),
    ('SIR', 'SIR_SAY_D', 'Sayxunobod tumani', 'Сайхунобод тумани', 'Сайхунабадский район', 'Sayxunobod District'),
    ('SIR', 'SIR_SAR_D', 'Sardoba tumani', 'Сардоба тумани', 'Сардобинский район', 'Sardoba District'),
    ('SIR', 'SIR_SIR_D', 'Sirdaryo tumani', 'Сирдарё тумани', 'Сырдарьинский район', 'Sirdaryo District'),

    -- Surxondaryo (SUR)
    ('SUR', 'SUR_TER_C', 'Termiz shahri', 'Термиз шаҳри', 'город Термез', 'Termez City'),
    ('SUR', 'SUR_ANG_D', 'Angor tumani', 'Ангор тумани', 'Ангорский район', 'Angor District'),
    ('SUR', 'SUR_BAN_D', 'Bandixon tumani', 'Бандихон тумани', 'Бандиханский район', 'Bandixon District'),
    ('SUR', 'SUR_BOY_D', 'Boysun tumani', 'Бойсун тумани', 'Байсунский район', 'Boysun District'),
    ('SUR', 'SUR_DEN_D', 'Denov tumani', 'Денов тумани', 'Денауский район', 'Denov District'),
    ('SUR', 'SUR_JAR_D', 'Jarqo''rg''on tumani', 'Жарқўрғон тумани', 'Джаркурганский район', 'Jarqurgon District'),
    ('SUR', 'SUR_QIZ_D', 'Qiziriq tumani', 'Қизириқ тумани', 'Кизирикский район', 'Qiziriq District'),
    ('SUR', 'SUR_QUM_D', 'Qumqo''rg''on tumani', 'Қумқўрғон тумани', 'Кумкурганский район', 'Qumqurgon District'),
    ('SUR', 'SUR_MUZ_D', 'Muzrabot tumani', 'Музработ тумани', 'Музрабадский район', 'Muzrabot District'),
    ('SUR', 'SUR_OLT_D', 'Oltinsoy tumani', 'Олтинсой тумани', 'Алтынсайский район', 'Oltinsoy District'),
    ('SUR', 'SUR_SAR_D', 'Sariosiyo tumani', 'Сариосиё тумани', 'Сарыассийский район', 'Sariosiyo District'),
    ('SUR', 'SUR_TER_D', 'Termiz tumani', 'Термиз тумани', 'Термезский район', 'Termez District'),
    ('SUR', 'SUR_UZU_D', 'Uzun tumani', 'Узун тумани', 'Узунский район', 'Uzun District'),
    ('SUR', 'SUR_SHE_D', 'Sherobod tumani', 'Шеробод тумани', 'Шерабадский район', 'Sherobod District'),
    ('SUR', 'SUR_SHO_D', 'Sho''rchi tumani', 'Шўрчи тумани', 'Шурчинский район', 'Shorchi District'),

    -- Tashkent City + Region (TAS)
    ('TAS', 'TAS_BEK_D', 'Bektemir tumani', 'Бектемир тумани', 'Бектемирский район', 'Bektemir District'),
    ('TAS', 'TAS_CHI_D', 'Chilonzor tumani', 'Чилонзор тумани', 'Чиланзарский район', 'Chilonzor District'),
    ('TAS', 'TAS_MIR_D', 'Mirzo Ulug''bek tumani', 'Мирзо Улуғбек тумани', 'Мирзо-Улугбекский район', 'Mirzo Ulugbek District'),
    ('TAS', 'TAS_MRO_D', 'Mirobod tumani', 'Миробод тумани', 'Мирабадский район', 'Mirobod District'),
    ('TAS', 'TAS_OLM_D', 'Olmazor tumani', 'Олмазор тумани', 'Алмазарский район', 'Olmazor District'),
    ('TAS', 'TAS_SER_D', 'Sergeli tumani', 'Сергели тумани', 'Сергелийский район', 'Sergeli District'),
    ('TAS', 'TAS_UCH_D', 'Uchtepa tumani', 'Учтепа тумани', 'Учтепинский район', 'Uchtepa District'),
    ('TAS', 'TAS_SHA_D', 'Shayxontohur tumani', 'Шайхонтоҳур тумани', 'Шайхантохурский район', 'Shayxontohur District'),
    ('TAS', 'TAS_YAS_D', 'Yashnobod tumani', 'Яшнобод тумани', 'Яшнободский район', 'Yashnobod District'),
    ('TAS', 'TAS_YUN_D', 'Yunusobod tumani', 'Юнусобод тумани', 'Юнусабадский район', 'Yunusobod District'),
    ('TAS', 'TAS_YAK_D', 'Yakkasaroy tumani', 'Яккасарой тумани', 'Яккасарайский район', 'Yakkasaroy District'),
    ('TAS', 'TAS_YAN_D', 'Yangihayot tumani', 'Янгиҳаёт тумани', 'Янгихаётский район', 'Yangihayot District'),
    ('TAS', 'TAS_NUR_C', 'Nurafshon shahri', 'Нурафшон шаҳри', 'город Нурафшан', 'Nurafshon City'),
    ('TAS', 'TAS_OLM_C', 'Olmaliq shahri', 'Олмалиқ шаҳри', 'город Алмалык', 'Olmaliq City'),
    ('TAS', 'TAS_ANG_C', 'Angren shahri', 'Ангрен шаҳри', 'город Ангрен', 'Angren City'),
    ('TAS', 'TAS_BEK_C', 'Bekobod shahri', 'Бекобод шаҳри', 'город Бекабад', 'Bekobod City'),
    ('TAS', 'TAS_CHR_C', 'Chirchiq shahri', 'Чирчиқ шаҳри', 'город Чирчик', 'Chirchiq City'),
    ('TAS', 'TAS_OHA_C', 'Ohangaron shahri', 'Оҳангарон шаҳри', 'город Ахангаран', 'Ohangaron City'),
    ('TAS', 'TAS_YNL_C', 'Yangiyo''l shahri', 'Янгийўл шаҳри', 'город Янгиюль', 'Yangiyol City'),
    ('TAS', 'TAS_OQQ_D', 'Oqqo''rg''on tumani', 'Оққўрғон тумани', 'Аккурганский район', 'Oqqurgon District'),
    ('TAS', 'TAS_OHA_D', 'Ohangaron tumani', 'Оҳангарон тумани', 'Ахангаранский район', 'Ohangaron District'),
    ('TAS', 'TAS_BEK_R', 'Bekobod tumani', 'Бекобод тумани', 'Бекабадский район', 'Bekobod District'),
    ('TAS', 'TAS_BOS_D', 'Bo''stonliq tumani', 'Бўстонлиқ тумани', 'Бостанлыкский район', 'Bustonliq District'),
    ('TAS', 'TAS_BOK_D', 'Bo''ka tumani', 'Бўка тумани', 'Букинский район', 'Boka District'),
    ('TAS', 'TAS_ZAN_D', 'Zangiota tumani', 'Зангиота тумани', 'Зангиатинский район', 'Zangiota District'),
    ('TAS', 'TAS_QIB_D', 'Қибрай tumani', 'Қибрай тумани', 'Кибрайский район', 'Qibray District'),
    ('TAS', 'TAS_QUY_D', 'Quyichirchiq tumani', 'Қуйичирчиқ тумани', 'Куйичирчикский район', 'Quyichirchiq District'),
    ('TAS', 'TAS_PAR_D', 'Parkent tumani', 'Паркент тумани', 'Паркентский район', 'Parkent District'),
    ('TAS', 'TAS_PIS_D', 'Piskent tumani', 'Пискент тумани', 'Пискентский район', 'Piskent District'),
    ('TAS', 'TAS_ORT_D', 'O''rtachirchiq tumani', 'Ўртачирчиқ тумани', 'Уртачирчикский район', 'Ortachirchiq District'),
    ('TAS', 'TAS_CHN_D', 'Chinoz tumani', 'Чиноз тумани', 'Чиназский район', 'Chinoz District'),
    ('TAS', 'TAS_YUQ_D', 'Yuqorichirchiq tumani', 'Юқоричирчиқ тумани', 'Юкоричирчикский район', 'Yuqorichirchiq District'),
    ('TAS', 'TAS_YNL_D', 'Yangiyo''l tumani', 'Янгийўл тумани', 'Янгиюльский район', 'Yangiyol District'),
    ('TAS', 'TAS_TOS_D', 'Toshkent tumani', 'Тошкент тумани', 'Ташкентский район', 'Toshkent District'),

    -- Xorazm (XOR)
    ('XOR', 'XOR_URG_C', 'Urganch shahri', 'Урганч шаҳри', 'город Ургенч', 'Urganch City'),
    ('XOR', 'XOR_XIV_C', 'Xiva shahri', 'Хива шаҳри', 'город Хива', 'Xiva City'),
    ('XOR', 'XOR_BOG_D', 'Bog''ot tumani', 'Боғот тумани', 'Багатский район', 'Bogot District'),
    ('XOR', 'XOR_GUR_D', 'Gurlan tumani', 'Гурлан тумани', 'Гурленский район', 'Gurlan District'),
    ('XOR', 'XOR_QOS_D', 'Qo''shko''пир tumani', 'Қўшкўпир тумани', 'Кошкупырский район', 'Qoshkopir District'),
    ('XOR', 'XOR_URG_D', 'Urganch tumani', 'Урганч тумани', 'Ургенчский район', 'Urganch District'),
    ('XOR', 'XOR_HAZ_D', 'Hazorasp tumani', 'Ҳазорасп тумани', 'Хазараспский район', 'Hazorasp District'),
    ('XOR', 'XOR_XON_D', 'Xonqa tumani', 'Хонқа тумани', 'Ханкинский район', 'Xonqa District'),
    ('XOR', 'XOR_XIV_D', 'Xiva tumani', 'Хива тумани', 'Хивинский район', 'Xiva District'),
    ('XOR', 'XOR_SHO_D', 'Shovot tumani', 'Шовот тумани', 'Шаватский район', 'Shovot District'),
    ('XOR', 'XOR_YAN_D', 'Yangiariq tumani', 'Янгиариқ тумани', 'Янгиарыкский район', 'Yangiariq District'),
    ('XOR', 'XOR_YAB_D', 'Yangibozor tumani', 'Янгибозор тумани', 'Янгибазарский район', 'Yangibozor District'),
    ('XOR', 'XOR_TUP_D', 'Tuproqqal''a tumani', 'Тупроққалъа тумани', 'Тупраккалинский район', 'Tuproqqala District'),

    -- Qoraqalpog'iston (QOR)
    ('QOR', 'QOR_NUK_C', 'Nukus shahri', 'Нукус шаҳри', 'город Нукус', 'Nukus City'),
    ('QOR', 'QOR_AMU_D', 'Amudaryo tumani', 'Амударё тумани', 'Амударьинский район', 'Amudaryo District'),
    ('QOR', 'QOR_BER_D', 'Beruniy tumani', 'Беруний тумани', 'Берунийский район', 'Beruniy District'),
    ('QOR', 'QOR_BOZ_D', 'Bo''zatov tumani', 'Бўзатов тумани', 'Бозатауский район', 'Bozatov District'),
    ('QOR', 'QOR_QRO_D', 'Qorao''zak tumani', 'Қораўзак тумани', 'Караузякский район', 'Qoraozak District'),
    ('QOR', 'QOR_KEG_D', 'Kegeyli tumani', 'Кегейли тумани', 'Кегейлийский район', 'Kegeyli District'),
    ('QOR', 'QOR_QON_D', 'Qo''ng''irot tumani', 'Қўнғирот тумани', 'Кунградский район', 'Qongirot District'),
    ('QOR', 'QOR_QAN_D', 'Qanliko''l tumani', 'Қанликўл тумани', 'Канлыкульский район', 'Qanlikol District'),
    ('QOR', 'QOR_MOY_D', 'Mo''ynoq tumani', 'Мўйноқ тумани', 'Муйнакский район', 'Moynoq District'),
    ('QOR', 'QOR_NUK_D', 'Nukus tumani', 'Нукус тумани', 'Нукусский район', 'Nukus District'),
    ('QOR', 'QOR_TAX_D', 'Taxiatosh tumani', 'Тахиатош тумани', 'Тахиаташский район', 'Taxiatosh District'),
    ('QOR', 'QOR_TXK_D', 'Taxtako''pir tumani', 'Тахтакўпир тумани', 'Тахтакупырский район', 'Taxtakopir District'),
    ('QOR', 'QOR_TOR_D', 'To''rtko''l tumani', 'Тўрткўл тумани', 'Турткульский район', 'Tortkol District'),
    ('QOR', 'QOR_XOJ_D', 'Xo''jayli tumani', 'Хўжайли тумани', 'Ходжейлийский район', 'Xojayli District'),
    ('QOR', 'QOR_CHM_D', 'Чимбой tumani', 'Чимбой тумани', 'Чимбайский район', 'Chimboy District'),
    ('QOR', 'QOR_SHU_D', 'Shumanay tumani', 'Шуманай тумани', 'Шуманайский район', 'Shumanay District'),
    ('QOR', 'QOR_ELL_D', 'Ellikqal''a tumani', 'Элликқалъа тумани', 'Элликкалинский район', 'Ellikqala District')
)
INSERT INTO districts (id, region_id, code, name_uz_latn, name_uz_cyrl, name_ru, name_en)
SELECT
  gen_random_uuid(),
  r.id,
  nd.code,
  nd.name_uz_latn,
  nd.name_uz_cyrl,
  nd.name_ru,
  nd.name_en
FROM new_districts nd
JOIN regions r ON r.code = nd.region_code
WHERE NOT EXISTS (
  SELECT 1 FROM districts d WHERE d.code = nd.code
);